-- DEPRECATED — do not use this file.
--
-- This was an early prototype schema using:
--   table: code_nodes  (renamed to code_chunks)
--   dim:   vector(1536)  (OpenAI, now replaced by 768-dim Gemini)
--   id:    uuid  (now bigserial)
--
-- The canonical, active schema is: database/schema.sql
-- Run that file in your Supabase SQL editor instead.
--
-- If you previously applied this file, clean up with:
--   DROP TABLE IF EXISTS code_nodes;
--   DROP FUNCTION IF EXISTS match_code_nodes;
-- Then apply database/schema.sql and run POST /index to reindex.
